* Sessions

** 1. Empathy session (30 minutes)
   :PROPERTIES:
   :Chapter:  0
   :Tools:    Pen and paper
   :END:

Took place Dec 6th, 11:30AM. 
** 2. Ideas session (30 minutes)
   :PROPERTIES:
   :Chapter:  0
   :Tools:    Pen and paper
   :END:

Dec 8th, 11:00 AM. 

Let's go into the ideation phase, while not leaving the immersion phase http://www.mjvinnovation.com/blog/three-phases-design-thinking-immersion-ideation-prototyping

** 3. Tools (30 minutes+)
   :PROPERTIES:
   :Tools:    Laptop
   :Chapter:  1
   :END:

Set up tools, starting with the editor. Atom, emacs, anything like
that, command line, how to work with it, minimal Linux, which is the
environment of choice. 
** 4. Perl 6 (30 minutes)

Set it up, understand the REPL. 

Install rakudobrew and start to work with it. Class itself took like 15 minutes, and the rest was devoted to compiling latest version of MoarVM. Note: the $ in the documentation can be mistaken for a command. 

** 5. What is free software (30 minutes)
Probably a good talk for a Sunday morning. What is free software and
free licenses, what they mean, what it's like to create and produce
free software, why everything we do when learning a language should be
free so that other benefit from it.  

We are telling the story of Java, how it is about to become the cash
crop of Oracle who's attempting to ask for licenses, and what kind of
licenses here are and what we should do about it. 


** 6. Teamwork with git (30 minutes)
