* Sessions

** 1. Empathy session (30 minutes)
   :PROPERTIES:
   :Chapter:  0
   :Tools:    Pen and paper
   :END:

Took place Dec 6th, 11:30AM. 
** 2. Ideas session (30 minutes)
   :PROPERTIES:
   :Chapter:  0
   :Tools:    Pen and paper
   :END:

Dec 8th, 11:00 AM. 

Let's go into the ideation phase, while not leaving the immersion phase http://www.mjvinnovation.com/blog/three-phases-design-thinking-immersion-ideation-prototyping

** 3. Tools (30 minutes+)
   :PROPERTIES:
   :Tools:    Laptop
   :Chapter:  1
   :END:

Set up tools, starting with the editor. Atom, emacs, anything like
that, command line, how to work with it, minimal Linux, which is the
environment of choice. 
** 4. Perl 6 (30 minutes)

Set it up, understand the REPL. 

Install rakudobrew and start to work with it. Class itself took like 15 minutes, and the rest was devoted to compiling latest version of MoarVM. Note: the $ in the documentation can be mistaken for a command. 

** 5. What is free software (30 minutes)

** 6. Teamwork with git (30 minutes)
